### ISSUE TITLE
Bug in plots struct construction [flightSim3D.m]

### ISSUE THREAD

**Issue by GYskyfall** [Noiredd/PEGAS-MATLAB#1]
When I run the program, Maltab gives an error

```
testShuttle
vehicleTools found a violation of lower throttle limit! Time calculated by this call will likely overestimate true burn time.
 Error: ()-indexing must appear last in an index expression.

 Error flightSim3D (line 391)
        plots().DEBUG = struct();

 Error flightManager (line 47)
    powered(1) = flightSim3D(vehicle, 1, init, s1guidance, events, dt);

 Error testShuttle (line 14)
STS = flightManager(vehicle, site, target, 0.2, stage1, 2, 0, []);
```

I don't know how to solve it, would you help me?

**Comment by Noiredd** [comment]
What MATLAB version are you using? The program was designed using ver. 2013a which is quite old by now.

**Comment by GYskyfall** [comment]
the version is matlab 2018a

**Comment by GYskyfall** [comment]
Would you please interpret this codes

  " plots().DEBUG = struct()"

**Comment by GYskyfall** [comment]
The way to solve the problem is to remove the brackets after PLOTS

  plots().DEBUG = struct();
transfer to:
  plots.DEBUG = struct();

**Comment by GYskyfall** [comment]
Another question:
 
Can this matlab programs support multi-ignitions during the launch mission?

**Comment by Noiredd** [comment]
Thank you for bringing this to my attention, @GYskyfall, and sorry it took me so long to respond (I'm not very active in this repo these days).

I took a look into it and pushed a fix. There are a few lines where the brackets should be omitted, see 26dba6a for details. To be honest, I don't know why it was necessary in 2013a - I just remember it didn't work without them.

To answer your question: yes, you can program multiple ignitions - you just need to define each iginition as a separate stage (yes this involves doing some math on masses and stuff).
