### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by GYskyfall** [Noiredd/PEGAS-MATLAB#2]
I am currently using Pegas to achieve deorbit module. To achieve a landing, the reference is [NASA_NTRS_Archive_19730023781](https://ntrs.nasa.gov/search.jsp?R=19730023781&hterms=19730023781&qs=N%3D0%26Ntk%3DAll%26Ntt%3D19730023781%26Ntx%3Dmode%2520matchallpartial).

Can you give me your email address so that I can ask you directly if I have any questions?

Do you have any recommended textbooks and papers that fully explain the principle of pegas? I still don’t fully understand the content of the program.

**Comment by Noiredd** [comment]
I am so sorry! I haven't been notified of this issue so I've only just noticed it.  
Just in case you still need help, be sure to read my [explanation of the algorithm](https://github.com/Noiredd/PEGAS-MATLAB/blob/master/docs/upfg.md), which includes the best sources I have found on the subject (listed at the bottom).

If you need to contact me directly, it would be better if you gave _me_ some way to contact you first. I'm sorry, I don't want to share my email publicly, but if you post your email here, I'll be sure to redact it from your post as soon as I send you a message.
